/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.12.7.0 (NJsonSchema v9.10.6.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export check AddColumn = {
    RowId: string | null,
    Widths: ColumnWidths | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check ColumnWidths = {
    Xs: number | null,
    Sm: number | null,
    Md: number | null,
    Lg: number | null,
}

export check RootId = {
    Type: RootType | null,
    Id: number | null,
}

export enum RootType {
    Site = 0, 
    Theme = 1, 
}

export check DeleteColumn = {
    ColumnId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check MoveColumnToRow = {
    ColumnId: string | null,
    RowId: string | null,
    AnchorColumnId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check SetColumnClasses = {
    ColumnId: string | null,
    Classes: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check SetColumnWidths = {
    ColumnId: string | null,
    Widths: ColumnWidths | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check AddComponentInstance = {
    ColumnId: string | null,
    AnchorColumnElementId: string | null,
    SiteComponentId: number | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check MoveComponentInstanceToColumn = {
    ComponentInstanceId: string | null,
    ColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check RemoveComponentInstance = {
    ComponentInstanceId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check AddComponentSlot = {
    ColumnId: string | null,
    AnchorColumnElementId: string | null,
    ThemeComponentId: number | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check MoveComponentSlotToColumn = {
    ComponentSlotId: string | null,
    ColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check RemoveComponentSlot = {
    ComponentSlotId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check AddDynamicComponentArea = {
    NewDynamicComponentAreaId: string | null,
    ColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check DeleteDynamicComponentArea = {
    DynamicComponentAreaId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check MoveDynamicComponentArea = {
    DynamicComponentAreaId: string | null,
    ColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check CreateLayout = {
    Name: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
    NewLayoutId: string | null,
}

export check DeleteLayout = {
    LayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check RenameLayout = {
    LayoutId: string | null,
    NewLayoutName: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check SetLayoutClasses = {
    LayoutId: string | null,
    Classes: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check ChangeDefaultLayout = {
    DefaultLayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check CreateSiteLayoutRoot = {
    SiteLayoutRootId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check CreateThemeLayoutRoot = {
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check UseLayoutOnPage = {
    PageId: number | null,
    LayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check CreateRowInColumn = {
    NewRowId: string | null,
    ColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check CreateRowInSection = {
    NewRowId: string | null,
    SectionId: string | null,
    AnchorRowId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check DeleteRow = {
    RowId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check MoveRowToColumn = {
    RowId: string | null,
    FromColumnId: string | null,
    ToColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check MoveRowToSection = {
    RowId: string | null,
    ToSectionId: string | null,
    AnchorRowId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check SetRowClasses = {
    RowId: string | null,
    Classes: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check CloneSectionToLayout = {
    NewSectionId: string | null,
    SectionId: string | null,
    LayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check CreateSection = {
    NewSectionId: string | null,
    LayoutId: string | null,
    Name: string | null,
    AnchorSectionId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check DeleteSection = {
    SectionId: string | null,
    LayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check ReapplyThemeOnSite = {
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check ApplyThemeToSite = {
    ThemeLayoutRootId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check LinkSectionToLayout = {
    SectionId: string | null,
    LayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check MoveSectionToLayout = {
    SectionId: string | null,
    ToLayoutId: string | null,
    FromLayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check RenameSection = {
    SectionId: string | null,
    NewName: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check SequenceSection = {
    SectionId: string | null,
    LayoutId: string | null,
    AnchorSectionId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check SetSectionClasses = {
    SectionId: string | null,
    Classes: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export check SetSectionWidth = {
    SectionId: string | null,
    Width: SectionWidth | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export enum SectionWidth {
    Full = 0, 
    Contained = 1, 
}


