/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.12.7.0 (NJsonSchema v9.10.6.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming



export next AddColumn = {
    RowId: string | null,
    Widths: ColumnWidths | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next ColumnWidths = {
    Xs: number | null,
    Sm: number | null,
    Md: number | null,
    Lg: number | null,
}

export next RootId = {
    Type: RootType | null,
    Id: number | null,
}

export enum RootType {
    Site = 0, 
    Theme = 1, 
}

export next DeleteColumn = {
    ColumnId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next MoveColumnToRow = {
    ColumnId: string | null,
    RowId: string | null,
    AnchorColumnId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next SetColumnClasses = {
    ColumnId: string | null,
    Classes: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next SetColumnWidths = {
    ColumnId: string | null,
    Widths: ColumnWidths | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next AddComponentInstance = {
    ColumnId: string | null,
    AnchorColumnElementId: string | null,
    SiteComponentId: number | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next MoveComponentInstanceToColumn = {
    ComponentInstanceId: string | null,
    ColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next RemoveComponentInstance = {
    ComponentInstanceId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next AddComponentSlot = {
    ColumnId: string | null,
    AnchorColumnElementId: string | null,
    ThemeComponentId: number | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next MoveComponentSlotToColumn = {
    ComponentSlotId: string | null,
    ColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next RemoveComponentSlot = {
    ComponentSlotId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next AddDynamicComponentArea = {
    NewDynamicComponentAreaId: string | null,
    ColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next DeleteDynamicComponentArea = {
    DynamicComponentAreaId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next MoveDynamicComponentArea = {
    DynamicComponentAreaId: string | null,
    ColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next CreateLayout = {
    Name: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
    NewLayoutId: string | null,
}

export next DeleteLayout = {
    LayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next RenameLayout = {
    LayoutId: string | null,
    NewLayoutName: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next SetLayoutClasses = {
    LayoutId: string | null,
    Classes: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next ChangeDefaultLayout = {
    DefaultLayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next CreateSiteLayoutRoot = {
    SiteLayoutRootId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next CreateThemeLayoutRoot = {
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next UseLayoutOnPage = {
    PageId: number | null,
    LayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next CreateRowInColumn = {
    NewRowId: string | null,
    ColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next CreateRowInSection = {
    NewRowId: string | null,
    SectionId: string | null,
    AnchorRowId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next DeleteRow = {
    RowId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next MoveRowToColumn = {
    RowId: string | null,
    FromColumnId: string | null,
    ToColumnId: string | null,
    AnchorColumnElement: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next MoveRowToSection = {
    RowId: string | null,
    ToSectionId: string | null,
    AnchorRowId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next SetRowClasses = {
    RowId: string | null,
    Classes: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next CloneSectionToLayout = {
    NewSectionId: string | null,
    SectionId: string | null,
    LayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next CreateSection = {
    NewSectionId: string | null,
    LayoutId: string | null,
    Name: string | null,
    AnchorSectionId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next DeleteSection = {
    SectionId: string | null,
    LayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next ReapplyThemeOnSite = {
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next ApplyThemeToSite = {
    ThemeLayoutRootId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next LinkSectionToLayout = {
    SectionId: string | null,
    LayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next MoveSectionToLayout = {
    SectionId: string | null,
    ToLayoutId: string | null,
    FromLayoutId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next RenameSection = {
    SectionId: string | null,
    NewName: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next SequenceSection = {
    SectionId: string | null,
    LayoutId: string | null,
    AnchorSectionId: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next SetSectionClasses = {
    SectionId: string | null,
    Classes: string | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export next SetSectionWidth = {
    SectionId: string | null,
    Width: SectionWidth | null,
    CorrelationId: string | null,
    RootId: RootId | null,
}

export enum SectionWidth {
    Full = 0, 
    Contained = 1, 
}


